name: Code Formatting (w/ Prettier)

on:
  pull_request:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Format code
        run: npm run format
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          message: 'ci: format code with Prettier'
